### ISSUE TITLE
Change Product Description

### ISSUE THREAD

**Issue by tankhashobhit** [cometa-rocks/cometa#22]
In the next update from today, please ensure that the product label is changed from "Complete Meta Test Automation" to "Complete Meta Test Platform".

Our capabilities now go beyond automation engineering.

**Comment by raro42** [comment]
done via commit b64910c..d1d7a33

**Comment by tankhashobhit** [comment]
Once the change happens, I will review the below images for a preliminary user-end review. 

![Screenshot (2)](https://github.com/cometa-rocks/cometa/assets/142929527/33754ee5-4ee1-4079-84ea-2c50d50dd7a6)
![Screenshot (3)](https://github.com/cometa-rocks/cometa/assets/142929527/42268c33-d77c-4c32-9ce9-0769665d9500)

**Comment by tankhashobhit** [comment]
@raro42 I am still seeing the above product description. When will my Prod URL show the changes?

**Comment by tankhashobhit** [comment]
![image](https://github.com/cometa-rocks/cometa/assets/142929527/9a974d32-7033-4681-b109-5068200811e1)

The issue is resolved. Great work.
